application: traffalert
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: .*
  script: main.app

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /crons
  script: crons.py
  login: admin

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"
#- name: dateutil
#  version: "2.1"
